### ISSUE TITLE
Function for the reading of QVAR data

### ISSUE THREAD

**Issue by ce97** [stm32duino/LSM6DSV16X#9]
Hi, I would like to know if it is possible to create a library or a function to acquire QVAR data as for example it is present for the ILPS22QS sensor using the Arduino IDE and a Nucleo-64 stm32 board.

**Comment by fpistm** [comment]
Linked to https://www.stm32duino.com/viewtopic.php?t=1963

**Comment by cparata** [comment]
Hello @ce97 ,
it's in the TODO list. I keep you informed when the QVAR support will be added to the library.
Best Regards,
Carlo

**Comment by ce97** [comment]
Thank you!

**Comment by cparata** [comment]
You can find QVAR support in the last release of the library. So we can close this issue.
